### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ThomWright**

### CODE REVIEW

**Comment by conradludgate** [comment]
What updated in retry-policies 👀

**Comment by conradludgate** [comment]
Looks good btw. However it might be a little while until I can release this as I'm on holiday 🌴

**Comment by conradludgate** [comment]
Found time at a computer. Published!

**Comment by ThomWright** [comment]
> What updated in retry-policies 👀

https://github.com/TrueLayer/retry-policies/pull/10

Have fun reading my essay of a PR 😄

**Pull request merged**
